import edu.uci.ics.jung.visualization.VisualizationViewer;

import java.util.ArrayList;

/**
 *
 * @author azhar
 */
public class ControlUI extends javax.swing.JFrame {

    /**
     * Creates new form ControlUI
     */

    private ArrayList<TokenNode> nodes=null;
    VisualizationViewer<TokenNode,Number> graphViewer=null;

    test mainObject;
    public ControlUI(test t) {

        mainObject=t;
        graphViewer=mainObject.graphVisualizer.graphViewer;
        nodes=new ArrayList<TokenNode>();


        initComponents();

        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane_HostList = new javax.swing.JScrollPane();
        jTextArea_MobileHosts = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_Select_MSS = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_CHL_Change = new javax.swing.JButton();
        jComboBox_CHL_New_MSS = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jComboBox_CHL_Old_MSS = new javax.swing.JComboBox();
        jComboBox_CHL_Host = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_CHL_Old_Proxy = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jComboBox_ChangeScheme = new javax.swing.JComboBox();
        jButton_CS_Change = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jComboBox_Request_MSS = new javax.swing.JComboBox();
        jComboBox_Request_MH = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Request_Proxy = new javax.swing.JComboBox();
        jButton_Request = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        Execute = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane_HostList1 = new javax.swing.JScrollPane();
        jTextArea_Output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Show Mobile Hosts"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("List Of Mobile Hosts"));

        jTextArea_MobileHosts.setEditable(false);
        jTextArea_MobileHosts.setColumns(20);
        jTextArea_MobileHosts.setRows(5);
        jScrollPane_HostList.setViewportView(jTextArea_MobileHosts);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_HostList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_HostList, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Select MSS/Proxy"));

        jComboBox_Select_MSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Select_MSSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jComboBox_Select_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox_Select_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("Select MSS");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation Terminal"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Host Location"));

        jLabel2.setText("New MSS");

        jButton_CHL_Change.setText("Change");
        jButton_CHL_Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CHL_ChangeActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Host"));

        jComboBox_CHL_Old_MSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CHL_Old_MSSActionPerformed(evt);
            }
        });

        jLabel1.setText("Current MSS");

        jLabel5.setText("Host");

        jLabel6.setText("Current Proxy");

        jComboBox_CHL_Old_Proxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CHL_Old_ProxyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel6))
                                        .addComponent(jComboBox_CHL_Old_Proxy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel1)
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel5)
                                                .addGap(49, 49, 49))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jComboBox_CHL_Old_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox_CHL_Host, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox_CHL_Old_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_CHL_Host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_CHL_Old_Proxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Current MSS");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBox_CHL_New_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel2)))
                                                .addGap(36, 36, 36)
                                                .addComponent(jButton_CHL_Change, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox_CHL_New_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton_CHL_Change))
                                .addGap(7, 7, 7))
        );

        jLabel2.getAccessibleContext().setAccessibleName("New MSS");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Schemes"));

        jComboBox_ChangeScheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inform Scheme", "Proxy Scheme", "Replication Scheme" }));

        jButton_CS_Change.setText("Change");
        jButton_CS_Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CS_ChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jComboBox_ChangeScheme, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_CS_Change)
                                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox_ChangeScheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton_CS_Change))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Make Request"));

        jComboBox_Request_MSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Request_MSSActionPerformed(evt);
            }
        });

        jLabel7.setText("Select MSS");

        jLabel8.setText("Select Host");

        jLabel9.setText("Select Proxy");

        jComboBox_Request_Proxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Request_ProxyActionPerformed(evt);
            }
        });

        jButton_Request.setText("Request");
        jButton_Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jComboBox_Request_Proxy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_Request)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jComboBox_Request_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox_Request_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox_Request_MSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_Request_MH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_Request_Proxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Request)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Execute"));

        Execute.setText("Execute");
        Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(Execute)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Execute)
                                .addGap(21, 21, 21))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        jTextArea_Output.setEditable(false);
        jTextArea_Output.setColumns(20);
        jTextArea_Output.setRows(5);
        jScrollPane_HostList1.setViewportView(jTextArea_Output);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_HostList1)
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_HostList1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.getAccessibleContext().setAccessibleName("Change Host MSS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void jComboBox_Select_MSSActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        jComboBox_Select_MSSActionPerformed();

    }


    private void jComboBox_CHL_Old_ProxyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jComboBox_CHL_Old_ProxyActionPerformed();
    }


    private void jComboBox_CHL_Old_MSSActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        jComboBox_CHL_Old_MSSActionPerformed();



    }



    private void jComboBox_Request_ProxyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jComboBox_Request_ProxyActionPerformed();
    }



    private void jComboBox_Request_MSSActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jComboBox_Request_MSSActionPerformed();
    }



    private void jButton_RequestActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        MobilHost mobilHost = (MobilHost)jComboBox_Request_MH.getSelectedItem();


        if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_INFORM){
            mobilHost.submitRequest(ProjectConstants.requestCounter.toString());

        }else if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){
                // add for proxy
            mobilHost.submitRequest_proxy(ProjectConstants.requestCounter.toString());

        }else {// for replication

            mobilHost.request(ProjectConstants.requestCounter.toString());
        }

        ProjectConstants.requestCounter++;
    }

    private void ExecuteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        TokenNode current_token_location=null;
        if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_INFORM){
            current_token_location=mainObject.tk.executeToken();
        }else if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){
            // add for proxy
            current_token_location=mainObject.tk.executeProxy();

        }else {// for replication
            current_token_location=mainObject.tk.execute_3();

        }
        nodes.add(current_token_location);
        simulate();
    }

    private void jButton_CS_ChangeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        if (ProjectConstants.CURRENT_SCHEME != jComboBox_ChangeScheme.getSelectedItem().toString()){
            ProjectConstants.CURRENT_SCHEME =jComboBox_ChangeScheme.getSelectedItem().toString();
            ProjectConstants.requestCounter=0;
            initializeChangeScheme();
        }

    }




    private void jButton_CHL_ChangeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        MobilHost selected_mh=(MobilHost)jComboBox_CHL_Host.getSelectedItem();

        MobilSupportServer new_mss=(MobilSupportServer)jComboBox_CHL_New_MSS.getSelectedItem();


        if (!new_mss.equals((MobilSupportServer)jComboBox_CHL_Old_MSS.getSelectedItem())){
            if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){
                selected_mh.moveTo_Proxy(new_mss);
            }else {

                selected_mh.moveTo(new_mss);
            }

            MobilSupportServer old_mss=(MobilSupportServer)jComboBox_CHL_Old_MSS.getSelectedItem();

            nodes.add(old_mss);
            nodes.add(new_mss);
            updateHostViews();
            simulate();


        }
    }

    private void updateHostViews(){
        MobilSupportServer selected_mss=(MobilSupportServer)jComboBox_CHL_Old_MSS.getSelectedItem();
        jComboBox_CHL_Host.removeAllItems();
        for (MobilHost h:selected_mss.userList){
            jComboBox_CHL_Host.addItem(h);
        }


        selected_mss=(MobilSupportServer)jComboBox_Request_MSS.getSelectedItem();
        jComboBox_Request_MH.removeAllItems();
        for (MobilHost h:selected_mss.userList){
            jComboBox_Request_MH.addItem(h);
        }

        jComboBox_Select_MSSActionPerformed();


    }

    private void simulate(){


        new Thread(){
            @Override
        public void run(){
                for (TokenNode n:nodes){
                    n.changeColor=true;
                    graphViewer.repaint();
                    try {
                        Thread.sleep(1000);
                    }catch (Exception ex){
                        ex.printStackTrace();
                    }

                }

                for (TokenNode n:nodes){
                    n.changeColor=false;
                }
                graphViewer.repaint();
                nodes.removeAll(nodes);
            }
        }.start();




    }

    private void initializeChangeScheme(){

        if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_INFORM){

            initializeInformScheme();

        }else if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){

            initializeProxyScheme();

        }else { // replication

            initializeReplicationScheme();

        }

        this.graphViewer=mainObject.graphVisualizer.graphViewer;

    }

    private void initializeInformScheme(){

        mainObject.initInfoScheme();

        jComboBox_CHL_Old_Proxy.removeAllItems();
        jComboBox_Request_Proxy.removeAllItems();
        jComboBox_Select_MSS.removeAllItems();



        // for change in select area
        for (TokenNode mss: mainObject.nodeList){
            jComboBox_Select_MSS.addItem(mss);
        }
        jComboBox_Select_MSSActionPerformed();


        //for change in "Change Host Location" area

        jComboBox_CHL_Old_MSS.removeAllItems();

        for (TokenNode mss:mainObject.nodeList){
            jComboBox_CHL_Old_MSS.addItem(mss);
        }
        jComboBox_CHL_Old_MSSActionPerformed();



        //for change in "Make Request" area

        jComboBox_Request_MSS.removeAllItems();

        for (TokenNode mss: mainObject.nodeList){
            jComboBox_Request_MSS.addItem(mss);
        }
        jComboBox_Request_MSSActionPerformed();


    }

    private void initializeProxyScheme(){

        mainObject.initProxyScheme();
        jComboBox_Select_MSS.removeAllItems();


        // for change in select area
        for (TokenNode proxy: mainObject.nodeList){
            jComboBox_Select_MSS.addItem(proxy);
        }



        jComboBox_Select_MSSActionPerformed();


        //for change in "Change Host Location" area

        jComboBox_CHL_Old_Proxy.removeAllItems();

        for (TokenNode mss:mainObject.nodeList){
            jComboBox_CHL_Old_Proxy.addItem(mss);
        }
        jComboBox_CHL_Old_ProxyActionPerformed();



        //for change in "Make Request" area

        jComboBox_Request_Proxy.removeAllItems();

        for (TokenNode proxy: mainObject.nodeList){
            jComboBox_Request_Proxy.addItem(proxy);
        }
        jComboBox_Request_ProxyActionPerformed();


    }

    private void initializeReplicationScheme(){

        mainObject.initReplicationScheme();
        jComboBox_CHL_Old_Proxy.removeAllItems();
        jComboBox_Request_Proxy.removeAllItems();



        jComboBox_Select_MSS.removeAllItems();


        // for change in select area
        for (TokenNode mss: mainObject.nodeList){
            jComboBox_Select_MSS.addItem(mss);
        }
        jComboBox_Select_MSSActionPerformed();


        //for change in "Change Host Location" area

        jComboBox_CHL_Old_MSS.removeAllItems();

        for (TokenNode mss:mainObject.nodeList){
            jComboBox_CHL_Old_MSS.addItem(mss);
        }
        jComboBox_CHL_Old_MSSActionPerformed();



        //for change in "Make Request" area

        jComboBox_Request_MSS.removeAllItems();

        for (TokenNode mss: mainObject.nodeList){
            jComboBox_Request_MSS.addItem(mss);
        }
        jComboBox_Request_MSSActionPerformed();

    }


    private void jComboBox_Request_ProxyActionPerformed() {
        // TODO add your handling code here:

        if(ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){

            Proxy selected_proxy=(Proxy)jComboBox_Request_Proxy.getSelectedItem();

            jComboBox_Request_MSS.removeAllItems();

            for (MobilSupportServer mss:selected_proxy.mssList){
                jComboBox_Request_MSS.addItem(mss);
            }

            jComboBox_Request_MSSActionPerformed();


        }
    }




    private void jComboBox_CHL_Old_ProxyActionPerformed() {
        // TODO add your handling code here:

        if(ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){

            Proxy selected_proxy=(Proxy)jComboBox_CHL_Old_Proxy.getSelectedItem();

            jComboBox_CHL_Old_MSS.removeAllItems();

            if (selected_proxy!=null){

                for (MobilSupportServer mss:selected_proxy.mssList){
                    jComboBox_CHL_Old_MSS.addItem(mss);
                }

            }

            jComboBox_CHL_Old_MSSActionPerformed();


        }
    }

    private void jComboBox_Select_MSSActionPerformed() {
        // TODO add your handling code here:

        if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){

            Proxy selected_proxy=(Proxy)jComboBox_Select_MSS.getSelectedItem();


            if (selected_proxy!=null){
                String text="";

                for (MobilSupportServer selected_mss:selected_proxy.mssList){

                    text+=selected_mss+" :---> \n";

                    for (MobilHost mh:selected_mss.userList){
                        text+="\t"+mh+"\n";
                    }

                }

                jTextArea_MobileHosts.setText(text);

            }


        }else {

            MobilSupportServer selected_mss=(MobilSupportServer)jComboBox_Select_MSS.getSelectedItem();

            String text="";

            if (selected_mss!=null){
                for (MobilHost mh:selected_mss.userList){
                    text+=mh+"\n";
                }
            }
            jTextArea_MobileHosts.setText(text);

        }


    }

    private void jComboBox_Request_MSSActionPerformed() {
        // TODO add your handling code here:
        MobilSupportServer selected_mss=(MobilSupportServer)jComboBox_Request_MSS.getSelectedItem();
        if (selected_mss!=null){
            jComboBox_Request_MH.removeAllItems();
            for (MobilHost mh:selected_mss.userList){
                jComboBox_Request_MH.addItem(mh);
            }
        }
    }

    private void jComboBox_CHL_Old_MSSActionPerformed() {
        // TODO add your handling code here:

        jComboBox_CHL_Host.removeAllItems();

        MobilSupportServer selected_mss=(MobilSupportServer)jComboBox_CHL_Old_MSS.getSelectedItem();


        if (selected_mss!=null){
            for (MobilHost mh: selected_mss.userList){
                jComboBox_CHL_Host.addItem(mh);

            }


            jComboBox_CHL_New_MSS.removeAllItems();

            if (ProjectConstants.CURRENT_SCHEME==ProjectConstants.SCHEME_PROXY){
                for (TokenNode node:mainObject.nodeList){
                    Proxy proxy=(Proxy)node;

                    for (MobilSupportServer mss:proxy.mssList){
                        if (!selected_mss.equals(mss)){
                            jComboBox_CHL_New_MSS.addItem(mss);

                        }
                    }

                }

            }else {

                for (TokenNode node:mainObject.nodeList){
                    if (!selected_mss.equals((MobilSupportServer)node)){
                        jComboBox_CHL_New_MSS.addItem(node);
                    }

                }

            }
        }

    }

    private void init(){

        ArrayList<TokenNode> mssList = mainObject.nodeList;



        //for mss
        for (TokenNode mss: mssList){

            // we are changing these comboboxes. so its event functions will be automatically called

            jComboBox_Select_MSS.addItem(mss);
            jComboBox_Request_MSS.addItem(mss);
            jComboBox_CHL_Old_MSS.addItem(mss);
        }




        /*
        MobilSupportServer selected_mss=(MobilSupportServer)jComboBox_CHL_Old_MSS.getSelectedItem();

        jComboBox_CHL_New_MSS.removeAllItems();
        for (TokenNode mss: mssList){
            if (!selected_mss.equals((MobilSupportServer)mss)){
                jComboBox_CHL_New_MSS.addItem(mss);

            }
        }



        //for host

        for (MobilHost mh: selected_mss.userList){
            jComboBox_CHL_Host.addItem(mh);
        }

        selected_mss=(MobilSupportServer)jComboBox_Request_MSS.getSelectedItem();
        for (MobilHost mh: selected_mss.userList){
            jComboBox_Request_MH.addItem(mh);
        }




        String text="";

        selected_mss=(MobilSupportServer)jComboBox_Select_MSS.getSelectedItem();

        if (selected_mss!=null)
        for (MobilHost mh:selected_mss.userList){
            text+=mh+"\n";
        }
        jTextArea_MobileHosts.setText(text);

        */




    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton Execute;
    private javax.swing.JButton jButton_CHL_Change;
    private javax.swing.JButton jButton_CS_Change;
    private javax.swing.JButton jButton_Request;
    private javax.swing.JComboBox jComboBox_CHL_Host;
    private javax.swing.JComboBox jComboBox_CHL_New_MSS;
    private javax.swing.JComboBox jComboBox_CHL_Old_MSS;
    private javax.swing.JComboBox jComboBox_CHL_Old_Proxy;
    private javax.swing.JComboBox jComboBox_ChangeScheme;
    private javax.swing.JComboBox jComboBox_Request_MH;
    private javax.swing.JComboBox jComboBox_Request_MSS;
    private javax.swing.JComboBox jComboBox_Request_Proxy;
    private javax.swing.JComboBox jComboBox_Select_MSS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane_HostList;
    private javax.swing.JScrollPane jScrollPane_HostList1;
    private javax.swing.JTextArea jTextArea_MobileHosts;
    private javax.swing.JTextArea jTextArea_Output;
    // End of variables declaration                   
}
